/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import Lab7.Admin;
import Lab7.AdminManager;
import Lab7.UserAccountManager;
import Lab7.InstructorManager;
import Lab7.StudentManager;
import Lab7.Course;
import Lab7.ApprovalStatus;
import Lab7.User;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.ArrayList;
/**
 *
 * @author adham
 */
public class AdminDashboardFrame extends javax.swing.JFrame {

   private Admin currentAdmin;
    private UserAccountManager accountManager;
    private AdminManager adminManager;
    private InstructorManager instructorManager;
    private StudentManager studentManager;
    private List<Course> pendingCourses;
    public AdminDashboardFrame() {
        initComponents();
        
    }
    public AdminDashboardFrame(
        Admin admin, 
        UserAccountManager accountManager, 
        AdminManager adminManager, 
        InstructorManager instructorManager, 
        StudentManager studentManager) {
        
        this.currentAdmin = admin;
        this.accountManager = accountManager;
        this.adminManager = adminManager;
        this.instructorManager = instructorManager;
        this.studentManager = studentManager;
        
        initComponents();
        this.setTitle("Admin Dashboard - Welcome " + admin.getUsername());
        
        // Load the data into the table upon opening the dashboard
        loadPendingCoursesTable();
    }
    private void loadPendingCoursesTable() {
        // 1. Get pending courses
        pendingCourses = adminManager.getPendingCourses();

        // 2. Define table columns
        String[] columnNames = {"Course ID", "Title", "Description", "Instructor Username", "Lessons"};

        // 3. Prepare data for the table model
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            // Make cells non-editable
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        for (Course course : pendingCourses) {
            String instructorUsername = "N/A";
            
            User instructor = accountManager.getUserById(course.getInstructorId());
            if (instructor != null) {
                instructorUsername = instructor.getUsername();
            } else {
                // Fallback: show the ID if username can't be fetched
                instructorUsername = course.getInstructorId() + " (User Not Found)";
            }
            
            Object[] row = new Object[]{
                course.getCourseId(),
                course.getTitle(),
                course.getDescription(),
                instructorUsername,
                course.getLessons().size()
            };
            model.addRow(row);
        }
        
        // 4. Set the model to the table
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        approve = new javax.swing.JToggleButton();
        reject = new javax.swing.JToggleButton();
        back = new javax.swing.JToggleButton();
        logout = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        approve.setText("approve");
        approve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveActionPerformed(evt);
            }
        });

        reject.setText("reject");
        reject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectActionPerformed(evt);
            }
        });

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(approve, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reject, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(approve)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reject)
                        .addGap(68, 68, 68)
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void approveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                "Please select a course to approve.", 
                "Selection Error", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Get the corresponding Course object from the list
        Course selectedCourse = pendingCourses.get(selectedRow);

        // Set the status to APPROVED and update the JSON file
        boolean success = adminManager.setCourseStatus(selectedCourse.getCourseId(), ApprovalStatus.APPROVED);

        if (success) {
            JOptionPane.showMessageDialog(this, 
                "Course \"" + selectedCourse.getTitle() + "\" APPROVED.", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
            // Refresh the table to show remaining pending courses
            loadPendingCoursesTable();
        } else {
            JOptionPane.showMessageDialog(this, 
                "Failed to approve course. Course ID not found or error occurred.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_approveActionPerformed

    private void rejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                "Please select a course to reject.", 
                "Selection Error", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Get the corresponding Course object from the list
        Course selectedCourse = pendingCourses.get(selectedRow);

        // Set the status to REJECTED and update the JSON file
        boolean success = adminManager.setCourseStatus(selectedCourse.getCourseId(), ApprovalStatus.REJECTED);

        if (success) {
            JOptionPane.showMessageDialog(this, 
                "Course \"" + selectedCourse.getTitle() + "\" REJECTED.", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
            // Refresh the table to show remaining pending courses
            loadPendingCoursesTable();
        } else {
            JOptionPane.showMessageDialog(this, 
                "Failed to reject course. Course ID not found or error occurred.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_rejectActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_backActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_logoutActionPerformed
    private void logout() {
    // Creates a new LoginFrame and passes the existing, loaded manager
    new LoginFrame(accountManager).setVisible(true); 
    this.dispose(); 
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton approve;
    private javax.swing.JToggleButton back;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton logout;
    private javax.swing.JToggleButton reject;
    // End of variables declaration//GEN-END:variables
}
