/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Lab7.Course; 
import Lab7.Instructor;
import Lab7.InstructorManager;
import Lab7.Student;
import Lab7.StudentManager; 
import Lab7.UserAccountManager;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
public class EnrolledStudentsFrame extends javax.swing.JFrame {

    private Instructor currentInstructor;
    private InstructorManager instructorManager;
    private StudentManager studentManager; 
    private DefaultTableModel tableModel;
    private UserAccountManager accountManager;
    public EnrolledStudentsFrame(Instructor instructor, InstructorManager im, StudentManager sm,UserAccountManager am) {
        initComponents();
        this.currentInstructor = instructor;
        this.instructorManager = im;
        this.studentManager = sm;
        this.accountManager = am;
        this.setLocationRelativeTo(null);
        setTitle("Enrolled Students for " + currentInstructor.getUsername() + "'s Courses");
        loadEnrolledStudentsTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        back = new javax.swing.JToggleButton();
        logout = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course Id", "Title ", "Student ID", "Username"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();

        InstructorDashboardFrame dashboard = new InstructorDashboardFrame(
            currentInstructor, 
            accountManager, 
            instructorManager,
           studentManager
        );
        dashboard.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
     
        // 2. Dispose of the current frame
        this.dispose();

        
        LoginFrame login = new LoginFrame(accountManager);
        login.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public void loadEnrolledStudentsTable() {
       DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
       tableModel.setRowCount(0);
       
        // 1. Get all course IDs created by the instructor
       List<String> courseIds = currentInstructor.getCreatedCourses();
    
    for (String courseId : courseIds) {
        Course course = instructorManager.getCourseById(courseId);
        
        if (course != null) {
            // 2. Get the list of student IDs enrolled in this course
            List<String> studentIds = course.getStudents();
            
            if (studentIds.isEmpty()) {
                // Show one row indicating no students
                Object[] rowData = new Object[] {
                    course.getCourseId(),
                    course.getTitle(),
                    "N/A",
                    "No Students Enrolled"
                };
                tableModel.addRow(rowData);
            } else {
                // 3. Iterate through each enrolled student ID
                for (String studentId : studentIds) {
                    
                    // 4. Look up Student details using StudentManager
                    Student student = studentManager.getStudentById(studentId);
                    
                    String studentUsername = (student != null) 
                            ? student.getUsername() 
                            : "UNKNOWN_USER (ID: " + studentId + ")";

                    // 5. Build the row data (ORDER MUST MATCH NETBEANS COLUMNS)
                    Object[] rowData = new Object[] {
                        course.getCourseId(),   // Column 1
                        course.getTitle(),      // Column 2
                        studentId,              // Column 3
                        studentUsername         // Column 4
                    };
                    
                    tableModel.addRow(rowData);
                }
            }
        }
    }
  }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton back;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton logout;
    // End of variables declaration//GEN-END:variables
}
