import Lab7.Course;
import Lab7.Lesson1;
import Lab7.Quiz1;
import Lab7.Result1;
import Lab7.Student;
import Lab7.User;
import Lab7.UserAccountManager;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class LessonsFrame extends javax.swing.JFrame {
    
    // Fields for functionality
    private UserAccountManager accountManager;
    private User currentUser;
    private String courseId;
    private DefaultTableModel model;

    /**
     * Creates new form LessonsFrame
     */
    public LessonsFrame(UserAccountManager accountManager, User currentUser, String courseId) {
        this.accountManager = accountManager;
        this.currentUser = currentUser;
        this.courseId = courseId;
        initComponents();

        // ADDED "Resources" to the columns list
        String[] columns = {"Lesson ID", "Title", "Content", "Resources", "Completed"};
        
        model = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        LessonsTable.setModel(model);

        loadLessons();
    }
    
    // Load lessons of the selected course
   private void loadLessons() {
        model.setRowCount(0);

        Course course = accountManager.getCourseById(courseId);
        if (course == null) return;

        List<Lesson1> lessons = course.getLessons();
        for (Lesson1 lesson : lessons) {
            boolean completed = false;
            if (currentUser instanceof Student) {
                Student student = (Student) currentUser;
                completed = student.isLessonCompleted(courseId, lesson.getLessonId());
            }
            
            // Convert the list of resources into a readable string
            // Example: "video.mp4, slides.pdf"
            String resourcesString = "";
            if (lesson.getResources() != null && !lesson.getResources().isEmpty()) {
                resourcesString = String.join(", ", lesson.getResources());
            } else {
                resourcesString = "None";
            }
            
            // Add the row with the new "resourcesString"
            model.addRow(new Object[]{
                lesson.getLessonId(), 
                lesson.getTitle(), 
                lesson.getContent(), 
                resourcesString, 
                completed
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        LessonsTable = new javax.swing.JTable();
        markCompletedButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        takeQuizbutton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LessonsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(LessonsTable);

        markCompletedButton.setText("Mark as Completed");
        markCompletedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markCompletedButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        takeQuizbutton.setText("take quiz");
        takeQuizbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeQuizbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(markCompletedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(takeQuizbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(517, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markCompletedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(takeQuizbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(380, Short.MAX_VALUE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void markCompletedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markCompletedButtonActionPerformed
     // 1. Get Selected Lesson
    int selectedRow = LessonsTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a lesson to mark as completed.", "Selection Error", JOptionPane.WARNING_MESSAGE);
        return;
    }
    String lessonId = (String) model.getValueAt(selectedRow, 0);

    // 2. Initial Checks
    if (!(currentUser instanceof Student)) {
        JOptionPane.showMessageDialog(this, "Only students can mark lessons as complete.", "Access Denied", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    Student student = (Student) currentUser;
    Course course = accountManager.getCourseById(courseId);
    if (course == null) return;

    Lesson1 lesson = course.getLessonById(lessonId);
    if (lesson == null) return;
    
    if (student.isLessonCompleted(courseId, lessonId)) {
        JOptionPane.showMessageDialog(this, "Lesson is already marked as completed.", "Status", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    // 3. Perform Quiz Check (The new requirement)
    Quiz1 quiz = lesson.getQuiz();
    int passingScore = lesson.getPassingScore(); 

    // A. Check for quiz availability
    if (quiz == null) {
        JOptionPane.showMessageDialog(this, 
            "The instructor has not created a quiz yet. This lesson cannot be marked complete.", 
            "No Quiz Available", JOptionPane.WARNING_MESSAGE);
        return; // BLOCK completion
    }

    // B. Check for passing score
    Result1 result = student.getResultForLesson(lessonId);

    if (result == null || result.getHighestScore() < passingScore) {
        JOptionPane.showMessageDialog(this, 
            "You must pass the quiz (score of " + passingScore + " or higher) before marking this lesson complete. " +
            "Your highest score is " + (result != null ? result.getHighestScore() : 0) + ".", 
            "Quiz Required", JOptionPane.WARNING_MESSAGE);
        return; // BLOCK completion
    }
    
    // 4. Mark Complete and Save
    student.markLessonCompleted(courseId, lessonId);
    accountManager.saveUser(student); // Saves the updated student object
    
    JOptionPane.showMessageDialog(this, "Lesson marked as completed!", "Success", JOptionPane.INFORMATION_MESSAGE);
    
    loadLessons();
    
    }//GEN-LAST:event_markCompletedButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // Return to the Enrolled Courses list
    EnrolledCoursesFrame enrolledFrame = new EnrolledCoursesFrame(accountManager, currentUser);
    enrolledFrame.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void takeQuizbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeQuizbuttonActionPerformed
        // TODO add your handling code here:
   int selectedRow = LessonsTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a lesson to take the quiz.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String lessonId = (String) model.getValueAt(selectedRow, 0);

        // Initial check for student status
        if (!(currentUser instanceof Student)) {
            JOptionPane.showMessageDialog(this, "Only students can take quizzes.", "Access Denied", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Student student = (Student) currentUser;

        // 2. Find Course and Lessons
        Course course = accountManager.getCourseById(courseId);
        if (course == null) return;

        List<Lesson1> allLessons = course.getLessons();
        Lesson1 lesson = null;
        int currentLessonIndex = -1;
        
        // Find the current lesson and its index (assumes lessons are ordered sequentially)
        for (int i = 0; i < allLessons.size(); i++) {
            if (allLessons.get(i).getLessonId().equals(lessonId)) {
                lesson = allLessons.get(i);
                currentLessonIndex = i;
                break;
            }
        }

        if (lesson == null) return; // Error: Lesson not found

        // 3. PREREQUISITE CHECK: Ensure the student has completed the previous lesson
        if (currentLessonIndex > 0) {
            Lesson1 previousLesson = allLessons.get(currentLessonIndex - 1);
            String previousLessonId = previousLesson.getLessonId();

            if (!student.isLessonCompleted(courseId, previousLessonId)) {
                JOptionPane.showMessageDialog(this, 
                    "You must successfully complete the quiz for the previous lesson, '" + previousLesson.getTitle() + "', before attempting this one.", 
                    "Prerequisite Required", JOptionPane.ERROR_MESSAGE);
                return; // BLOCK the quiz
            }
        }
        // End of PREREQUISITE CHECK

        // 4. Check for Quiz Availability
        Quiz1 quiz = lesson.getQuiz();
        if (quiz == null) {
            JOptionPane.showMessageDialog(this,
                "The instructor has not created a quiz for this lesson yet.",
                "No Quiz Available", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // 5. Check for Max Retries (Existing Logic)
        Result1 result = student.getResultForLesson(lessonId);

        if (result != null && result.hasReachedMaxRetries()) {
             JOptionPane.showMessageDialog(this, "You have reached the maximum number of retries for this quiz.",
                     "Max Retries Reached", JOptionPane.ERROR_MESSAGE);
             return;
        }

        // 6. Launch the QuizFrame
        QuizFrame quizFrame = new QuizFrame(accountManager, student, courseId, lesson);
        quizFrame.setVisible(true);
    }//GEN-LAST:event_takeQuizbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LessonsTable;
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton markCompletedButton;
    private javax.swing.JToggleButton takeQuizbutton;
    // End of variables declaration//GEN-END:variables
}
