import javax.swing.*;
import Lab7.Course;
import Lab7.InstructorManager;
import Lab7.Lesson1;
import Lab7.Question1;
import Lab7.Quiz1;
import Lab7.UserAccountManager;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.UUID;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author adham
 */
public class ManageLessonsFrame extends javax.swing.JFrame {

    private Course course;
    private InstructorManager instructorManager;
    private DefaultTableModel tableModel;
    private managecourses parentFrame;
    private UserAccountManager accountManager;
    public ManageLessonsFrame(Course course, InstructorManager manager, managecourses parent, UserAccountManager accountManager) {
        this.course = course;
        this.instructorManager = manager;
        this.parentFrame = parent; // Store parent reference
        this.accountManager = accountManager; // Store manager reference
        
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Manage Lessons for: " + course.getTitle() + " (" + course.getCourseId() + ")");
        loadLessonsTable();
        
    }
    public void loadLessonsTable() {
        // Use the existing model and clear rows to preserve column names
        DefaultTableModel tableModel = (DefaultTableModel) lessonsTable.getModel();
        tableModel.setRowCount(0); // Clear existing rows

        // Check if getLessons() exists and returns a List<Lesson>
        List<Lesson1> lessons = course.getLessons(); 
        
        if (lessons != null) {
            for (Lesson1 lesson : lessons) {
                // Truncate content for a cleaner table view
                String content = lesson.getContent();
                String truncatedContent = content.length() > 80 ? content.substring(0, 77) + "..." : content;
                
                Object[] rowData = new Object[] {
                    lesson.getLessonId(),
                    lesson.getTitle(),
                    truncatedContent
                };
                tableModel.addRow(rowData);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lessonsTable = new javax.swing.JTable();
        addlesson = new javax.swing.JToggleButton();
        deletelesson = new javax.swing.JToggleButton();
        back = new javax.swing.JToggleButton();
        logout = new javax.swing.JToggleButton();
        createQuizButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lessonsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "LessonId", "Title", "Content"
            }
        ));
        jScrollPane1.setViewportView(lessonsTable);

        addlesson.setText("add lesson");
        addlesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addlessonActionPerformed(evt);
            }
        });

        deletelesson.setText("delete lesson");
        deletelesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletelessonActionPerformed(evt);
            }
        });

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        createQuizButton.setText("Create Quiz");
        createQuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createQuizButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addlesson, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletelesson, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createQuizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(addlesson)
                        .addGap(18, 18, 18)
                        .addComponent(deletelesson)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createQuizButton)
                        .addGap(21, 21, 21)
                        .addComponent(back)
                        .addGap(18, 18, 18)
                        .addComponent(logout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addlessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addlessonActionPerformed
        // TODO add your handling code here:
        String lessonId = JOptionPane.showInputDialog(this, "Enter new Lesson ID (e.g., L1, L2):", "Add Lesson", JOptionPane.QUESTION_MESSAGE);
        if (lessonId == null || lessonId.trim().isEmpty()) return;
        lessonId = lessonId.trim();

        // Validation: Check for Lesson ID uniqueness within the course
        if (course.getLessonById(lessonId) != null) {
            JOptionPane.showMessageDialog(this, "A lesson with ID '" + lessonId + "' already exists.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Prompt for Title
        String title = JOptionPane.showInputDialog(this, "Enter Lesson Title:", "Add Lesson", JOptionPane.QUESTION_MESSAGE);
        if (title == null || title.trim().isEmpty()) return;
        title = title.trim();

        // 3. Prompt for Content
        String content = JOptionPane.showInputDialog(this, "Enter Lesson Content:", "Add Lesson", JOptionPane.QUESTION_MESSAGE);
        if (content == null || content.trim().isEmpty()) return;
        content = content.trim();
        
        // 4. Call Manager to create and save the lesson
        Lesson1 newLesson = instructorManager.createLesson(
            course, 
            lessonId, 
            title, 
            content
        );

        if (newLesson != null) {
            JOptionPane.showMessageDialog(this, "Lesson '" + title + "' added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadLessonsTable(); // Refresh the table
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add lesson.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addlessonActionPerformed

    private void deletelessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletelessonActionPerformed
        // TODO add your handling code here:
        int selectedRow = lessonsTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a lesson to delete.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 2. Retrieve the Lesson ID and Title from the selected row (Lesson ID is at column index 0)
        String lessonId = (String) lessonsTable.getModel().getValueAt(selectedRow, 0);
        String lessonTitle = (String) lessonsTable.getModel().getValueAt(selectedRow, 1);
        
        // 3. Retrieve the Lesson object from the Course
        Lesson1 lessonToDelete = course.getLessonById(lessonId);

        if (lessonToDelete == null) {
            // Should not happen if data is loaded correctly, but safe to check
            JOptionPane.showMessageDialog(this, "Error: Could not find lesson with ID '" + lessonId + "'.", "System Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 4. Confirmation Dialog
        int response = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete lesson: " + lessonTitle + " (" + lessonId + ")?\nThis is a permanent action.", 
            "Confirm Lesson Deletion", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.WARNING_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            
            // 5. Call Manager to delete and save
            boolean success = instructorManager.deleteLesson(course, lessonToDelete);
            
            if (success) {
                JOptionPane.showMessageDialog(this, "Lesson '" + lessonTitle + "' deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadLessonsTable(); // Refresh the table
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete lesson.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deletelessonActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        if (accountManager != null) {
            
            // 1. Perform the backend logout
            accountManager.logout();
            JOptionPane.showMessageDialog(this, "You have been successfully logged out.", "Logout Successful", JOptionPane.INFORMATION_MESSAGE);
            
            // 2. Close this frame
            this.dispose(); 
            
            // 3. Close the parent frame (managecourses)
            if (parentFrame != null) {
                parentFrame.dispose(); 
            }
            
            // 4. Open the LoginFrame
            try {
                // Ensure LoginFrame is accessible and accepts UserAccountManager
                LoginFrame loginFrame = new LoginFrame(accountManager); 
                loginFrame.setVisible(true);
            } catch (Exception e) {
                System.err.println("Could not reopen LoginFrame: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void createQuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createQuizButtonActionPerformed
                                   
    // TODO add your handling code here:
    int selectedRow = lessonsTable.getSelectedRow();
    
    // 1. Check for selected lesson
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a lesson first.", "Selection Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Retrieve the selected Lesson1 object
    // Assuming lesson ID is in column 0
    String lessonId = (String) lessonsTable.getModel().getValueAt(selectedRow, 0);
    Lesson1 selectedLesson = course.getLessonById(lessonId);  // Ensure course has this method
    
    if (selectedLesson == null) {
        JOptionPane.showMessageDialog(this, "Selected lesson not found.", "Internal Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Check if a quiz already exists
    if (selectedLesson.getQuiz() != null) {
        int confirm = JOptionPane.showConfirmDialog(this, 
            "A quiz already exists for this lesson. Do you want to overwrite it?", 
            "Quiz Exists", 
            JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
    }

    // 2. Get Quiz Metadata
    String quizTitle = JOptionPane.showInputDialog(this, "Enter the Quiz Title:", "Quiz Creation", JOptionPane.QUESTION_MESSAGE);
    if (quizTitle == null || quizTitle.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Quiz creation cancelled or invalid title.", "Cancelled", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int passingScore = 0;
    try {
        String scoreStr = JOptionPane.showInputDialog(this, "Enter the Passing Score (e.g., 70):", "Quiz Creation", JOptionPane.QUESTION_MESSAGE);
        if (scoreStr == null) return; // User cancelled
        passingScore = Integer.parseInt(scoreStr.trim());
        if (passingScore < 0 || passingScore > 100) {
            JOptionPane.showMessageDialog(this, "Passing score must be between 0 and 100.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid score entered. Please enter a whole number.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int numQuestions = 0;
    try {
        String numStr = JOptionPane.showInputDialog(this, "Enter the Number of Questions:", "Quiz Creation", JOptionPane.QUESTION_MESSAGE);
        if (numStr == null) return; // User cancelled
        numQuestions = Integer.parseInt(numStr.trim());
        if (numQuestions <= 0) {
            JOptionPane.showMessageDialog(this, "Number of questions must be greater than zero.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid number entered. Please enter a whole number.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    List<Question1> questions = new ArrayList<>();
    
    // 3. Loop to gather all questions
    for (int i = 1; i <= numQuestions; i++) {
        String questionText = JOptionPane.showInputDialog(this, "Question " + i + ": Enter the question text:", "Question Details", JOptionPane.QUESTION_MESSAGE);
        
        // --- ADDED CHECK: Question cannot be empty ---
        if (questionText == null || questionText.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Question " + i + " text cannot be empty. Quiz creation aborted.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // ---------------------------------------------

        List<String> options = new ArrayList<>();
        // Gather 4 choices/options
        for (int j = 1; j <= 4; j++) {
            String option = JOptionPane.showInputDialog(this, 
                "Question " + i + ": Enter Choice " + j + ":", 
                "Question Details", 
                JOptionPane.QUESTION_MESSAGE);
            
            // --- ADDED CHECK: Option cannot be empty ---
            if (option == null || option.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Choice " + j + " for Question " + i + " cannot be empty. Quiz creation aborted.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            // --------------------------------------------
            options.add(option);
        }

        int correctIndex = -1; // 0-based index
        try {
            String correctStr = JOptionPane.showInputDialog(this, 
                "Question " + i + ": Enter the CORRECT Choice number (1, 2, 3, or 4):", 
                "Question Details", 
                JOptionPane.QUESTION_MESSAGE);
            if (correctStr == null) {
                JOptionPane.showMessageDialog(this, "Correct answer entry cancelled. Quiz creation aborted.", "Cancelled", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int choiceNumber = Integer.parseInt(correctStr.trim());
            if (choiceNumber < 1 || choiceNumber > 4) {
                JOptionPane.showMessageDialog(this, "Correct choice must be 1, 2, 3, or 4.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            correctIndex = choiceNumber - 1; 
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid choice number. Please enter 1, 2, 3, or 4.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Create and add the Question1 object
        Question1 newQuestion = new Question1(questionText, options, correctIndex);
        questions.add(newQuestion);
    }
    
    // 4. Create Quiz1 object
    // Assuming UUID is imported (java.util.UUID)
    String quizId = UUID.randomUUID().toString();
    Quiz1 newQuiz = new Quiz1(quizId, quizTitle, passingScore);
    for(Question1 q : questions) {
        newQuiz.addQuestion(q);
    }

    // 5. Attach quiz to lesson and save
    boolean success = instructorManager.setLessonQuiz(course, selectedLesson, newQuiz);
    
    if (success) {
        JOptionPane.showMessageDialog(this, "Quiz '" + quizTitle + "' created and attached to lesson: " + selectedLesson.getTitle(), "Success", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Failed to save the quiz. Please check backend logic.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_createQuizButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addlesson;
    private javax.swing.JToggleButton back;
    private javax.swing.JToggleButton createQuizButton;
    private javax.swing.JToggleButton deletelesson;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lessonsTable;
    private javax.swing.JToggleButton logout;
    // End of variables declaration//GEN-END:variables
}
