
import Lab7.Course;
import Lab7.InstructorManager;
import Lab7.Lesson;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author adham
 */
public class ManageLessonsFrame extends javax.swing.JFrame {

    private Course course;
    private InstructorManager instructorManager;
    private DefaultTableModel tableModel;
    public ManageLessonsFrame(Course course, InstructorManager manager) {
        initComponents();
        this.course = course;
        this.instructorManager = manager;
        this.setLocationRelativeTo(null);
        setTitle("Manage Lessons for: " + course.getTitle() + " (" + course.getCourseId() + ")");
        loadLessonsTable();
    }
    public void loadLessonsTable() {
        // Use the existing model and clear rows to preserve column names
        DefaultTableModel tableModel = (DefaultTableModel) lessonsTable.getModel();
        tableModel.setRowCount(0); // Clear existing rows

        // Check if getLessons() exists and returns a List<Lesson>
        List<Lesson> lessons = course.getLessons(); 
        
        if (lessons != null) {
            for (Lesson lesson : lessons) {
                // Truncate content for a cleaner table view
                String content = lesson.getContent();
                String truncatedContent = content.length() > 80 ? content.substring(0, 77) + "..." : content;
                
                Object[] rowData = new Object[] {
                    lesson.getLessonId(),
                    lesson.getTitle(),
                    truncatedContent
                };
                tableModel.addRow(rowData);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lessonsTable = new javax.swing.JTable();
        addlesson = new javax.swing.JToggleButton();
        deletelesson = new javax.swing.JToggleButton();
        completed = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lessonsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "lessonID", "Title", "Content", "Completed"
            }
        ));
        jScrollPane1.setViewportView(lessonsTable);

        addlesson.setText("add lesson");
        addlesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addlessonActionPerformed(evt);
            }
        });

        deletelesson.setText("delete lesson");
        deletelesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletelessonActionPerformed(evt);
            }
        });

        completed.setText("mark as completed");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(completed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deletelesson, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addlesson, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(addlesson)
                        .addGap(35, 35, 35)
                        .addComponent(deletelesson)
                        .addGap(35, 35, 35)
                        .addComponent(completed, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addlessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addlessonActionPerformed

        String lessonId = JOptionPane.showInputDialog(this, "Enter new Lesson ID (e.g., L1, L2):", "Add Lesson", JOptionPane.QUESTION_MESSAGE);
        if (lessonId == null || lessonId.trim().isEmpty()) return;
        lessonId = lessonId.trim();

        // Validation: Check for Lesson ID uniqueness within the course
        if (course.getLessonById(lessonId) != null) {
            JOptionPane.showMessageDialog(this, "A lesson with ID '" + lessonId + "' already exists.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Prompt for Title
        String title = JOptionPane.showInputDialog(this, "Enter Lesson Title:", "Add Lesson", JOptionPane.QUESTION_MESSAGE);
        if (title == null || title.trim().isEmpty()) return;
        title = title.trim();

        // 3. Prompt for Content
        String content = JOptionPane.showInputDialog(this, "Enter Lesson Content:", "Add Lesson", JOptionPane.QUESTION_MESSAGE);
        if (content == null || content.trim().isEmpty()) return;
        content = content.trim();
        
        // 4. Call Manager to create and save the lesson
        Lesson newLesson = instructorManager.createLesson(
            course, 
            lessonId, 
            title, 
            content
        );

        if (newLesson != null) {
            JOptionPane.showMessageDialog(this, "Lesson '" + title + "' added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadLessonsTable(); // Refresh the table
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add lesson.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addlessonActionPerformed

    private void deletelessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletelessonActionPerformed
        // TODO add your handling code here:
        int selectedRow = lessonsTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a lesson to delete.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 2. Retrieve the Lesson ID and Title from the selected row (Lesson ID is at column index 0)
        String lessonId = (String) lessonsTable.getModel().getValueAt(selectedRow, 0);
        String lessonTitle = (String) lessonsTable.getModel().getValueAt(selectedRow, 1);
        
        // 3. Retrieve the Lesson object from the Course
        Lesson lessonToDelete = course.getLessonById(lessonId);

        if (lessonToDelete == null) {
            // Should not happen if data is loaded correctly, but safe to check
            JOptionPane.showMessageDialog(this, "Error: Could not find lesson with ID '" + lessonId + "'.", "System Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 4. Confirmation Dialog
        int response = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete lesson: " + lessonTitle + " (" + lessonId + ")?\nThis is a permanent action.", 
            "Confirm Lesson Deletion", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.WARNING_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            
            // 5. Call Manager to delete and save
            boolean success = instructorManager.deleteLesson(course, lessonToDelete);
            
            if (success) {
                JOptionPane.showMessageDialog(this, "Lesson '" + lessonTitle + "' deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadLessonsTable(); // Refresh the table
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete lesson.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    }//GEN-LAST:event_deletelessonActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addlesson;
    private javax.swing.JToggleButton completed;
    private javax.swing.JToggleButton deletelesson;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lessonsTable;
    // End of variables declaration//GEN-END:variables
}
