/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author adham
 */
import Lab7.InstructorManager;
import Lab7.Course; // Assuming Course class is in Lab7 package
import Lab7.Instructor;
import Lab7.Lesson;
import Lab7.StudentManager;
import Lab7.UserAccountManager; // Needed if you want to perform a full logout
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.util.List;
public class managecourses extends javax.swing.JFrame {
    private Instructor currentInstructor;
    private InstructorManager instructorManager;
    private UserAccountManager accountManager;
    private StudentManager studentManager;
  private DefaultTableModel tableModel;
    public managecourses(Instructor instructor, InstructorManager manager, UserAccountManager accountManager,StudentManager studentManager ) {
        initComponents();
        this.currentInstructor = instructor;
        this.instructorManager = manager;
        this.accountManager = accountManager;
        this.studentManager = studentManager;
       this.setLocationRelativeTo(null);
        setTitle("Manage Courses - Welcome, " + currentInstructor.getUsername());
        loadCoursesTable();
        
    }
    public void loadCoursesTable() {
        // We define 5 relevant columns, overriding the generic titles from initComponents
        String[] columnNames = {"ID", "Title", "Description", "Lessons", "Students"};
        
        tableModel = new DefaultTableModel(columnNames, 0) {
            // Override to make cells non-editable
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        // Get the list of course IDs created by the instructor
        List<String> courseIds = currentInstructor.getCreatedCourses();
        
        for (String courseId : courseIds) {
            // Fetch the full Course object using the Manager
            Course course = instructorManager.getCourseById(courseId);
            
            if (course != null) {
                // Truncate description for a cleaner table view
                String desc = course.getDescription();
                String truncatedDesc = desc.length() > 60 ? desc.substring(0, 57) + "..." : desc;
                
                // Prepare the row data
                Object[] rowData = new Object[] {
                    course.getCourseId(),
                    course.getTitle(),
                    truncatedDesc,
                    course.getLessons().size(), 
                    course.getStudents().size() 
                };
                
                tableModel.addRow(rowData);
            }
        }
        
        // Apply the prepared model to the JTable
        jtable1.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtable1 = new javax.swing.JTable();
        create = new javax.swing.JToggleButton();
        edit = new javax.swing.JToggleButton();
        logout = new javax.swing.JToggleButton();
        delete = new javax.swing.JToggleButton();
        back = new javax.swing.JToggleButton();
        addlesson = new javax.swing.JToggleButton();
        deletelessons = new javax.swing.JToggleButton();
        managelessons = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "courseId", "Title", "description", "lessons", "Students"
            }
        ));
        jScrollPane1.setViewportView(jtable1);

        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        edit.setText("edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        addlesson.setText("add lesson");
        addlesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addlessonActionPerformed(evt);
            }
        });

        deletelessons.setText("delete lessons");
        deletelessons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletelessonsActionPerformed(evt);
            }
        });

        managelessons.setText("manage lessons");
        managelessons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managelessonsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(create, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deletelessons, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addlesson, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(managelessons, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(create)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(managelessons)
                .addGap(24, 24, 24)
                .addComponent(deletelessons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(back)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addlesson)
                .addGap(109, 109, 109))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
      // 1. Hide the current frame (managecourses)
    this.setVisible(false);
    
    // 2. Create and show the new creation frame, passing 'this' (the managecourses frame)
    createFrame createCourseFrame = new createFrame(
        this.currentInstructor,
        this.instructorManager,
        this.accountManager,
        this // <--- Pass reference to this frame
    );
    createCourseFrame.setVisible(true);
    }//GEN-LAST:event_createActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        int selectedRow = jtable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to edit.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String courseId = (String) jtable1.getModel().getValueAt(selectedRow, 0);
        Course courseToEdit = instructorManager.getCourseById(courseId);

        if (courseToEdit != null) {
            String newTitle = JOptionPane.showInputDialog(this, "Enter new Title:", courseToEdit.getTitle());
            
            if (newTitle == null || newTitle.trim().isEmpty()) return; 

            String newDescription = JOptionPane.showInputDialog(this, "Enter new Description:", courseToEdit.getDescription());
            
            if (newDescription == null || newDescription.trim().isEmpty()) return; 

            // editCourse handles saving to courses.json
            boolean success = instructorManager.editCourse(courseToEdit, newTitle.trim(), newDescription.trim());

            if (success) {
                JOptionPane.showMessageDialog(this, "Course updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadCoursesTable(); 
            } else {
                JOptionPane.showMessageDialog(this, "Course update failed.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
      int selectedRow = jtable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to delete.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String courseId = (String) jtable1.getModel().getValueAt(selectedRow, 0);
        String courseTitle = (String) jtable1.getModel().getValueAt(selectedRow, 1);
        
        // Retrieve the Course object needed for the manager method call
        Course courseToDelete = instructorManager.getCourseById(courseId); 

        int response = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete the course: " + courseTitle + "?\nThis is a permanent action.", 
            "Confirm Deletion", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.WARNING_MESSAGE);

        if (response == JOptionPane.YES_OPTION && courseToDelete != null) {
            
            // 1. Call Manager: Manager deletes course from main list, removes ID from instructor, and saves courses.json.
            boolean removedFromCourses = instructorManager.deleteCourse(currentInstructor, courseToDelete); 
            
            if (removedFromCourses) {
                // 2. Save the updated Instructor object to users.json (since the manager modified currentInstructor)
                accountManager.saveUser(currentInstructor); 
                
                JOptionPane.showMessageDialog(this, 
                    "Course '" + courseTitle + "' deleted successfully. Changes saved to JSON.", 
                    "Success", JOptionPane.INFORMATION_MESSAGE);
                
                loadCoursesTable(); // Refresh the table display
                
            } else {
                JOptionPane.showMessageDialog(this, "Course deletion failed. The course may not exist.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        accountManager.logout();
        
        // 2. Display confirmation message
        JOptionPane.showMessageDialog(this, 
            "You have been successfully logged out.", 
            "Logout Successful", 
            JOptionPane.INFORMATION_MESSAGE
        );
        
        // 3. Close the current dashboard frame
        this.dispose(); 
        
        // 4. Open the Login Frame again to restart the session
        // NOTE: You must have a class named LoginFrame available in your project.
        try {
            LoginFrame loginFrame = new LoginFrame(accountManager);
            loginFrame.setVisible(true);
        } catch (Exception e) {
            // Fallback if LoginFrame creation fails (e.g., if it's not imported or defined)
            System.err.println("Could not reopen LoginFrame: " + e.getMessage());
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
   this.dispose();

    // 2. Open the Instructor Dashboard, passing the necessary managers and the current user
    try {
        // NOTE: InstructorDashboardFrame must be correctly imported and accept these parameters.
        InstructorDashboardFrame dashboard = new InstructorDashboardFrame(
            this.currentInstructor,
            this.accountManager,
            this.instructorManager,
            this.studentManager
        );
        dashboard.setVisible(true);
    } catch (Exception e) {
        // This catch block runs if the InstructorDashboardFrame class is missing 
        // or if its constructor signature is incorrect.
        JOptionPane.showMessageDialog(
            this,
            "Could not open the Instructor Dashboard. Check class definition.",
            "Navigation Error",
            JOptionPane.ERROR_MESSAGE
        );
        System.err.println("Error opening Dashboard: " + e.getMessage());
    }
    }//GEN-LAST:event_backActionPerformed

    private void addlessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addlessonActionPerformed
        // TODO add your handling code here:
        int selectedRow = jtable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to add a lesson to.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 1. Get the selected Course
        String courseId = (String) jtable1.getModel().getValueAt(selectedRow, 0);
        Course courseToEdit = instructorManager.getCourseById(courseId);

        if (courseToEdit != null) {
            
            // 2. Prompt for Lesson ID
            String lessonId = JOptionPane.showInputDialog(this, "Enter new Lesson ID (e.g., L1, L2):", "Add Lesson", JOptionPane.QUESTION_MESSAGE);
            if (lessonId == null || lessonId.trim().isEmpty()) return;
            
            // Validation: Check for Lesson ID uniqueness within the course
            if (courseToEdit.getLessonById(lessonId.trim()) != null) {
                JOptionPane.showMessageDialog(this, "A lesson with ID '" + lessonId.trim() + "' already exists in course '" + courseToEdit.getTitle() + "'.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 3. Prompt for Title
            String title = JOptionPane.showInputDialog(this, "Enter Lesson Title:", "Add Lesson", JOptionPane.QUESTION_MESSAGE);
            if (title == null || title.trim().isEmpty()) return;

            // 4. Prompt for Content
            // Using a JTextArea in a JOptionPane can improve usability for content, but for simplicity, we use the standard input dialog
            String content = JOptionPane.showInputDialog(this, "Enter Lesson Content:", "Add Lesson", JOptionPane.QUESTION_MESSAGE);
            if (content == null || content.trim().isEmpty()) return;
            
            // 5. Call Manager to create and save the lesson
            // This assumes your InstructorManager has the method: public Lesson createLesson(Course course, String lessonId, String title, String content)
            Lesson newLesson = instructorManager.createLesson(
                courseToEdit, 
                lessonId.trim(), 
                title.trim(), 
                content.trim()
            );

            if (newLesson != null) {
                JOptionPane.showMessageDialog(this, "Lesson '" + title.trim() + "' added successfully to course " + courseToEdit.getTitle() + ".", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadCoursesTable(); // Refresh the table to show updated lesson count
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add lesson.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_addlessonActionPerformed

    private void deletelessonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletelessonsActionPerformed
        // TODO add your handling code here:
        int selectedRow = jtable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to delete a lesson from.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 1. Get the selected Course
        String courseId = (String) jtable1.getModel().getValueAt(selectedRow, 0);
        Course courseToEdit = instructorManager.getCourseById(courseId);
        String courseTitle = courseToEdit.getTitle();

        if (courseToEdit != null) {
            
            // 2. Prompt for Lesson ID
            String lessonId = JOptionPane.showInputDialog(this, "Enter the ID of the lesson to delete:", "Delete Lesson", JOptionPane.QUESTION_MESSAGE);
            if (lessonId == null || lessonId.trim().isEmpty()) return;
            
            // 3. Retrieve the Lesson object
            Lesson lessonToDelete = courseToEdit.getLessonById(lessonId.trim());

            if (lessonToDelete == null) {
                JOptionPane.showMessageDialog(this, "Lesson with ID '" + lessonId.trim() + "' was not found in course '" + courseTitle + "'.", "Lesson Not Found", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // 4. Confirmation Dialog
            int response = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to delete lesson: " + lessonToDelete.getTitle() + " (" + lessonId.trim() + ") from course " + courseTitle + "?\nThis is a permanent action.", 
                "Confirm Lesson Deletion", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE);

            if (response == JOptionPane.YES_OPTION) {
                
                // 5. Call Manager to delete and save
                boolean success = instructorManager.deleteLesson(courseToEdit, lessonToDelete);
                
                if (success) {
                    JOptionPane.showMessageDialog(this, "Lesson '" + lessonToDelete.getTitle() + "' deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    loadCoursesTable(); // Refresh the table to show updated lesson count
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete lesson.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_deletelessonsActionPerformed

    private void managelessonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managelessonsActionPerformed
        // TODO add your handling code here:
        int selectedRow = jtable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to manage lessons.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 1. Get the selected Course
        String courseId = (String) jtable1.getModel().getValueAt(selectedRow, 0);
        Course courseToEdit = instructorManager.getCourseById(courseId);

        if (courseToEdit != null) {
            // 2. Open the new ManageLessonsFrame
            ManageLessonsFrame manageLessonsFrame = new ManageLessonsFrame(
                courseToEdit, 
                this.instructorManager
            );
            manageLessonsFrame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Error: Could not retrieve course details.", "System Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_managelessonsActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addlesson;
    private javax.swing.JToggleButton back;
    private javax.swing.JToggleButton create;
    private javax.swing.JToggleButton delete;
    private javax.swing.JToggleButton deletelessons;
    private javax.swing.JToggleButton edit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable1;
    private javax.swing.JToggleButton logout;
    private javax.swing.JToggleButton managelessons;
    // End of variables declaration//GEN-END:variables
}
