/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author adham
 */
import Lab7.InstructorManager;
import Lab7.Course; // Assuming Course class is in Lab7 package
import Lab7.Instructor;
//import Lab7.LoginFrame; // Assuming LoginFrame is available for full application restart
import Lab7.UserAccountManager; // Needed if you want to perform a full logout
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.util.List;
public class managecourses extends javax.swing.JFrame {
    private Instructor currentInstructor;
    private InstructorManager instructorManager;
    private UserAccountManager accountManager;
  private DefaultTableModel tableModel;
    public managecourses(Instructor instructor, InstructorManager manager, UserAccountManager accountManager) {
        initComponents();
        this.currentInstructor = instructor;
        this.instructorManager = manager;
        this.accountManager = accountManager;
       
        setTitle("Manage Courses - Welcome, " + currentInstructor.getUsername());
        loadCoursesTable();
        
    }
    private void loadCoursesTable() {
        // We define 5 relevant columns, overriding the generic titles from initComponents
        String[] columnNames = {"ID", "Title", "Description", "Lessons", "Students"};
        
        tableModel = new DefaultTableModel(columnNames, 0) {
            // Override to make cells non-editable
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        // Get the list of course IDs created by the instructor
        List<String> courseIds = currentInstructor.getCreatedCourses();
        
        for (String courseId : courseIds) {
            // Fetch the full Course object using the Manager
            Course course = instructorManager.getCourseById(courseId);
            
            if (course != null) {
                // Truncate description for a cleaner table view
                String desc = course.getDescription();
                String truncatedDesc = desc.length() > 60 ? desc.substring(0, 57) + "..." : desc;
                
                // Prepare the row data
                Object[] rowData = new Object[] {
                    course.getCourseId(),
                    course.getTitle(),
                    truncatedDesc,
                    // Assuming Course has getLessons() which returns a list/collection
                    course.getLessons().size(), 
                    // Assuming Course has getStudents() which returns a list/collection
                    course.getStudents().size() 
                };
                
                tableModel.addRow(rowData);
            }
        }
        
        // Apply the prepared model to the JTable
        jtable1.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtable1 = new javax.swing.JTable();
        create = new javax.swing.JToggleButton();
        edit = new javax.swing.JToggleButton();
        logout = new javax.swing.JToggleButton();
        delete = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "courseId", "Title", "description", "lessons", "Students"
            }
        ));
        jScrollPane1.setViewportView(jtable1);

        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        edit.setText("edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(create, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(create)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        int selectedRow = jtable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to edit.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String courseId = (String) jtable1.getModel().getValueAt(selectedRow, 0);
        Course courseToEdit = instructorManager.getCourseById(courseId);

        if (courseToEdit != null) {
            String newTitle = JOptionPane.showInputDialog(this, "Enter new Title:", courseToEdit.getTitle());
            
            if (newTitle == null || newTitle.trim().isEmpty()) return; 

            String newDescription = JOptionPane.showInputDialog(this, "Enter new Description:", courseToEdit.getDescription());
            
            if (newDescription == null || newDescription.trim().isEmpty()) return; 

            // editCourse handles saving to courses.json
            boolean success = instructorManager.editCourse(courseToEdit, newTitle.trim(), newDescription.trim());

            if (success) {
                JOptionPane.showMessageDialog(this, "Course updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadCoursesTable(); 
            } else {
                JOptionPane.showMessageDialog(this, "Course update failed.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
      int selectedRow = jtable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to delete.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String courseId = (String) jtable1.getModel().getValueAt(selectedRow, 0);
        String courseTitle = (String) jtable1.getModel().getValueAt(selectedRow, 1);
        
        // Retrieve the Course object needed for the manager method call
        Course courseToDelete = instructorManager.getCourseById(courseId); 

        int response = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete the course: " + courseTitle + "?\nThis is a permanent action.", 
            "Confirm Deletion", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.WARNING_MESSAGE);

        if (response == JOptionPane.YES_OPTION && courseToDelete != null) {
            
            // 1. Call Manager: Manager deletes course from main list, removes ID from instructor, and saves courses.json.
            boolean removedFromCourses = instructorManager.deleteCourse(currentInstructor, courseToDelete); 
            
            if (removedFromCourses) {
                // 2. Save the updated Instructor object to users.json (since the manager modified currentInstructor)
                accountManager.saveUser(currentInstructor); 
                
                JOptionPane.showMessageDialog(this, 
                    "Course '" + courseTitle + "' deleted successfully. Changes saved to JSON.", 
                    "Success", JOptionPane.INFORMATION_MESSAGE);
                
                loadCoursesTable(); // Refresh the table display
                
            } else {
                JOptionPane.showMessageDialog(this, "Course deletion failed. The course may not exist.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton create;
    private javax.swing.JToggleButton delete;
    private javax.swing.JToggleButton edit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable1;
    private javax.swing.JToggleButton logout;
    // End of variables declaration//GEN-END:variables
}
