/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author adham
 */
import Lab7.InstructorManager;
import Lab7.Course; // Assuming Course class is in Lab7 package
import Lab7.Instructor;
import Lab7.Lesson1;
import Lab7.Student;
import Lab7.StudentManager;
import Lab7.UserAccountManager; // Needed if you want to perform a full logout
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import org.jfree.data.category.DefaultCategoryDataset;

public class managecourses extends javax.swing.JFrame {

    private Instructor currentInstructor;
    private InstructorManager instructorManager;
    private UserAccountManager accountManager;
    private StudentManager studentManager;
    private DefaultTableModel tableModel;
    private InstructorDashboardFrame insFrame;

    public managecourses(Instructor instructor, InstructorManager manager, UserAccountManager accountManager, StudentManager studentManager, InstructorDashboardFrame insFrame) {
        initComponents();
        this.currentInstructor = instructor;
        this.instructorManager = manager;
        this.accountManager = accountManager;
        this.studentManager = studentManager;
        this.insFrame = insFrame;
        this.setLocationRelativeTo(null);
        setTitle("Manage Courses - Welcome, " + currentInstructor.getUsername());
        loadCoursesTable();

    }
    Course course;

    public void loadCoursesTable() {
        String[] columnNames = {"ID", "Title", "Description", "Lessons", "Students", "Status"};

        tableModel = new DefaultTableModel(columnNames, 0) {
            // Override to make cells non-editable
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // Get the list of course IDs created by the instructor
        List<String> courseIds = currentInstructor.getCreatedCourses();

        for (String courseId : courseIds) {
            // Fetch the full Course object using the Manager
            course = instructorManager.getCourseById(courseId);
            /*DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            for (int i = 0; i <= allcourses.size(); i++) {
                Course c = sm.getCourseById(allcourses.get(i));
                allcourses.add(course);
            }*/
            if (course != null) {
                // Truncate description for a cleaner table view
                String desc = course.getDescription();
                String truncatedDesc = desc.length() > 60 ? desc.substring(0, 57) + "..." : desc;
                String statusString = course.getStatus().name();

                // 3. Prepare the row data (now 6 elements)
                Object[] rowData = new Object[]{
                    course.getCourseId(),
                    course.getTitle(),
                    truncatedDesc,
                    course.getLessons().size(),
                    course.getStudents().size(),
                    statusString
                };

                tableModel.addRow(rowData);
            }
        }

        // Apply the prepared model to the JTable
        jtable1.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtable1 = new javax.swing.JTable();
        create = new javax.swing.JToggleButton();
        edit = new javax.swing.JToggleButton();
        logout = new javax.swing.JToggleButton();
        delete = new javax.swing.JToggleButton();
        back = new javax.swing.JToggleButton();
        managelessons = new javax.swing.JToggleButton();
        viewavg = new javax.swing.JButton();
        viewanalytics = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "courseId", "Title", "description", "lessons", "Students", "status"
            }
        ));
        jScrollPane1.setViewportView(jtable1);

        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        edit.setText("edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        managelessons.setText("manage lessons");
        managelessons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managelessonsActionPerformed(evt);
            }
        });

        viewavg.setText("Insight");
        viewavg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewavgActionPerformed(evt);
            }
        });

        viewanalytics.setText("view analytics");
        viewanalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewanalyticsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(managelessons))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewavg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewanalytics, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create)
                    .addComponent(edit)
                    .addComponent(delete))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(managelessons)
                            .addComponent(viewavg))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(viewanalytics)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout)
                    .addComponent(back))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // 1. Hide the current frame (managecourses)
        this.setVisible(false);

        // 2. Create and show the new creation frame, passing 'this' (the managecourses frame)
        createFrame createCourseFrame = new createFrame(
                this.currentInstructor,
                this.instructorManager,
                this.accountManager,
                this // <--- Pass reference to this frame
        );
        createCourseFrame.setVisible(true);
    }//GEN-LAST:event_createActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        int selectedRow = jtable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to edit.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String courseId = (String) jtable1.getModel().getValueAt(selectedRow, 0);
        Course courseToEdit = instructorManager.getCourseById(courseId);

        if (courseToEdit != null) {
            String newTitle = JOptionPane.showInputDialog(this, "Enter new Title:", courseToEdit.getTitle());

            if (newTitle == null || newTitle.trim().isEmpty()) {
                return;
            }

            String newDescription = JOptionPane.showInputDialog(this, "Enter new Description:", courseToEdit.getDescription());

            if (newDescription == null || newDescription.trim().isEmpty()) {
                return;
            }

            // editCourse handles saving to courses.json
            boolean success = instructorManager.editCourse(courseToEdit, newTitle.trim(), newDescription.trim());

            if (success) {
                JOptionPane.showMessageDialog(this, "Course updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadCoursesTable();
            } else {
                JOptionPane.showMessageDialog(this, "Course update failed.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = jtable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to delete.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String courseId = (String) jtable1.getModel().getValueAt(selectedRow, 0);
        String courseTitle = (String) jtable1.getModel().getValueAt(selectedRow, 1);

        // Retrieve the Course object needed for the manager method call
        Course courseToDelete = instructorManager.getCourseById(courseId);

        int response = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete the course: " + courseTitle + "?\nThis is a permanent action.",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (response == JOptionPane.YES_OPTION && courseToDelete != null) {

            // 1. Call Manager: Manager deletes course from main list, removes ID from instructor, and saves courses.json.
            boolean removedFromCourses = instructorManager.deleteCourse(currentInstructor, courseToDelete);

            if (removedFromCourses) {
                // 2. Save the updated Instructor object to users.json (since the manager modified currentInstructor)
                accountManager.saveUser(currentInstructor);

                JOptionPane.showMessageDialog(this,
                        "Course '" + courseTitle + "' deleted successfully. Changes saved to JSON.",
                        "Success", JOptionPane.INFORMATION_MESSAGE);

                loadCoursesTable(); // Refresh the table display

            } else {
                JOptionPane.showMessageDialog(this, "Course deletion failed. The course may not exist.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        accountManager.logout();

        // 2. Display confirmation message
        JOptionPane.showMessageDialog(this,
                "You have been successfully logged out.",
                "Logout Successful",
                JOptionPane.INFORMATION_MESSAGE
        );

        // 3. Close the current dashboard frame
        this.dispose();

        // 4. Open the Login Frame again to restart the session
        // NOTE: You must have a class named LoginFrame available in your project.
        try {
            LoginFrame loginFrame = new LoginFrame(accountManager);
            loginFrame.setVisible(true);
        } catch (Exception e) {
            // Fallback if LoginFrame creation fails (e.g., if it's not imported or defined)
            System.err.println("Could not reopen LoginFrame: " + e.getMessage());
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();

        // 2. Open the Instructor Dashboard, passing the necessary managers and the current user
        try {
            // NOTE: InstructorDashboardFrame must be correctly imported and accept these parameters.
            InstructorDashboardFrame dashboard = new InstructorDashboardFrame(
                    this.currentInstructor,
                    this.accountManager,
                    this.instructorManager,
                    this.studentManager
            );
            dashboard.setVisible(true);
        } catch (Exception e) {
            // This catch block runs if the InstructorDashboardFrame class is missing 
            // or if its constructor signature is incorrect.
            JOptionPane.showMessageDialog(
                    this,
                    "Could not open the Instructor Dashboard. Check class definition.",
                    "Navigation Error",
                    JOptionPane.ERROR_MESSAGE
            );
            System.err.println("Error opening Dashboard: " + e.getMessage());
        }
    }//GEN-LAST:event_backActionPerformed

    private void managelessonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managelessonsActionPerformed
        // TODO add your handling code here:
        int selectedRow = jtable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to manage lessons.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 1. Get the selected Course
        String courseId = (String) jtable1.getModel().getValueAt(selectedRow, 0);
        Course courseToEdit = instructorManager.getCourseById(courseId);

        if (courseToEdit != null) {
            // 2. Open the new ManageLessonsFrame
            ManageLessonsFrame manageLessonsFrame = new ManageLessonsFrame(
                    courseToEdit,
                    this.instructorManager,
                    this,
                    this.accountManager
            );
            manageLessonsFrame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Error: Could not retrieve course details.", "System Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_managelessonsActionPerformed

    private void viewavgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewavgActionPerformed
        int selectedRow = jtable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course.");
            return;
        }
        String courseId = jtable1.getValueAt(selectedRow, 0).toString();
        Course course1 = instructorManager.getCourse(courseId);
        if (course == null) {
            JOptionPane.showMessageDialog(this, "NULL COURSE");
        }
        chart c = new chart(insFrame, course1, studentManager);
    }//GEN-LAST:event_viewavgActionPerformed

    private void viewanalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewanalyticsActionPerformed
        // TODO add your handling code here:
        int selectedRow = jtable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course.");
            return;
        }
        String courseId = jtable1.getValueAt(selectedRow, 0).toString();

        // 1. Fetch the correct course object
        Course course1 = instructorManager.getCourseById(courseId);

        if (course1 == null) {
            JOptionPane.showMessageDialog(this, "Course data not found.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Open the Chart1 frame, passing the selected course and the student manager
        // Assuming 'chart' is the Chart1 class
        Chart1 chartFrame = new Chart1(course1, studentManager, this);
        chartFrame.setVisible(true);
    }//GEN-LAST:event_viewanalyticsActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton back;
    private javax.swing.JToggleButton create;
    private javax.swing.JToggleButton delete;
    private javax.swing.JToggleButton edit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable1;
    private javax.swing.JToggleButton logout;
    private javax.swing.JToggleButton managelessons;
    private javax.swing.JToggleButton viewanalytics;
    private javax.swing.JButton viewavg;
    // End of variables declaration//GEN-END:variables
}
